### ISSUE TITLE
Allow External Id usage in `update` && `registerUpdate`

### ISSUE THREAD

**Issue by zhiburt** [forcedotcom/sf-fx-runtime-java#315]
Hello,

I've noticed that update doesn't support external id usage even though Salesforce REST Api supports it.
 
I tend to believe It's enough to delete this exception and add the Id argument in update function. 

https://github.com/forcedotcom/sf-fx-runtime-java/blob/68e2e824b97fbbe5fefac8147ca3cad1b93ef24e/sf-fx-runtime-java-sdk-impl-v1/src/main/java/com/salesforce/functions/jvm/runtime/sdk/DataApiImpl.java#L155-L161

Thanks.
Take care.

ref: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_upsert.htm

**Comment by edmorley** [comment]
Hi! Sorry for the delayed reply. New features are not being added unfortunately, since Salesforce Functions is being retired:
https://devcenter.heroku.com/articles/salesforce-functions-retirement
